# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180127_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
