# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-31 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180127_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emainverifyreord',
            name='send_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emainverifyreord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '密码')], max_length=10, verbose_name='验证类型'),
        ),
    ]
