# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180508_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emainverifyreord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '密码'), ('update_email', '修改邮箱')], max_length=20, verbose_name='验证类型'),
        ),
    ]
