# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-27 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180127_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_num',
            new_name='click_nums',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='fav_number',
            new_name='fav_nums',
        ),
    ]
