# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180209_2148'),
        ('course', '0004_auto_20180131_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseOrg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
