# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端', max_length=50, verbose_name='课程类别'),
        ),
    ]
